#ifndef defs_H
#define defs_H

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>

#include <debug.h>

#define FILE_HEADER                                                            \
        "; 8086 ASM\n Generated by dasm8086"                                   \
        "; Michel Hardenberg"                                                  \
        "; This software is provided 'as-is', without any express or implied"  \
        "; warranty. In no event will the authors be held liable for any "     \
        "damages"                                                              \
        "; arising from the use of this software."

#define OUT_FILENAME_LEN 256
#endif // defs_H
