#include <defs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

const char header[1024] =
    "; 8086 ASM\n Generated by dasm8086"
    "; Michel Hardenberg"
    "; This software is provided 'as-is', without any express or implied"
    "; warranty. In no event will the authors be held liable for any damages"
    "; arising from the use of this software.";

#define OUT_FILENAME_LEN 256

enum Operation { DEFAULT_OP = 0, MOV_OP };

typedef struct {
        enum Operation op;
        unsigned char direction;
        unsigned char width;
        unsigned char reg;
        unsigned char rm;
} Instruction;

typedef struct {
        size_t size;
        size_t cap;
        Instruction *data;
} IList;

IList *createIList(size_t prealloc) {
        IList *list = malloc(sizeof(IList));
        list->cap = prealloc;
        list->size = 0;

        list->data = malloc(list->cap * sizeof(Instruction));
        return list;
}

void destroyIList(IList *list) {
        free(list->data);
        free(list);
}

int reallocIList(IList * const list, const unsigned int growthFac) {
        if (growthFac < 2) {
                return 1;
        }

        Instruction *newData = malloc(growthFac * list->cap * sizeof(Instruction));
        if (newData == NULL) {
                return 1;
        }

        list->cap *= growthFac;
        memcpy(newData, list->data, sizeof(Instruction) * list->size);
        free(list->data);
        list->data = newData;
        return 0;
}

int pushBackIList(IList *list, Instruction *item) {
        if (list == NULL && item == NULL) {
                return 1;
        }

        // check cap
        if (list->size == list->cap) {
                if (reallocIList(list, 2)) {
                        return 1;
                }
        }

        // append item
        list->data[list->size] = *item;
        list->size++;
        return 0;
}

int main(int argc, char **argv) {
        assert(argc >= 2);
        if (argv[1] == NULL) {
                LOGERROR("failed to open file. Aborting..");
        }

        FILE *binFile = fopen(argv[1], "rb");

        if (binFile == NULL) {
                LOGERROR("failed to open file. Aborting..");
                return 1;
        }

        IList *instructions = createIList(2);
        Instruction inst;
        char bytes[2];

        while (fread(&bytes, sizeof(char), 2, binFile)) {
                LOG("%hhx %hhx", bytes[0], bytes[1]);
                inst.op = MOV_OP;
                inst.direction = 1;
                inst.width = 2;
                inst.reg = 111;
                inst.rm = 222;
                if (pushBackIList(instructions, &inst)) {
                        LOGERROR("Failed to append to list");
                }
        };

        fclose(binFile);
        destroyIList(instructions);
        return 0;
}
