#include <defs.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

const char header[1024] =
    "; 8086 ASM\n Generated by dasm8086"
    "; Michel Hardenberg"
    "; This software is provided 'as-is', without any express or implied"
    "; warranty. In no event will the authors be held liable for any damages"
    "; arising from the use of this software.";

#define OUT_FILENAME_LEN 256

int main(int argc, char **argv) {
        assert(argc >= 2);
        if (argv[1] == NULL) {
                LOGERROR("failed to open file. Aborting..");
        }

        char outPath[OUT_FILENAME_LEN];
        const char outPathEnding[] = ".asm";

        size_t i = 0;
        char *c = argv[1];

        do {
                if (*c == '\0') break;
                if (*c == '/') {
                        i = 0;
                        ++c;
                        continue;
                }

                outPath[i] = *c;
                ++c;
                ++i;
        } while (c != NULL && i < OUT_FILENAME_LEN);
        strcpy(outPath + i, outPathEnding);

        LOG("out: %s", outPath);

        FILE *binFile = fopen(argv[1], "rb");
        FILE *asmFile = fopen(outPath, "a");

        if (binFile == NULL) {
                LOGERROR("failed to open file. Aborting..");
                return 1;
        }

        char bytes[2];
        while (fread(&bytes, sizeof(char), 2, binFile)) {
                LOG("%hhx %hhx", bytes[0], bytes[1]);
        };

        fclose(binFile);

        return 0;
}
